name: Semgrep SAST scan - For a better security in our repositories

permissions: write-all

on:
  workflow_call:
    inputs:
      working-directory:
        default: '.'
        required: false
        type: string
      is-blocking:
        required: false
        type: boolean
        default: true

jobs:
  semgrep:
    permissions:
        contents: read           # pour checkout et lecture du code source
        actions: read            # pour lire le contexte d'exécution GitHub Actions
        id-token: write          # pour l'authentification OIDC si besoin
        security-events: write   # pour uploader les fichiers SARIF dans GHAS
    timeout-minutes: 60
    runs-on: [self-hosted, Linux, standard]
    steps:
      - name: Informations
        continue-on-error: ${{ inputs.is-blocking == true && false || true }}
        run: |
          echo "BLOCKING WORKFLOW: ${{ inputs.is-blocking }}"
          echo "SCAN LOCATION: ${{ inputs.working-directory }}"

      - name: Checkout code
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        uses: actions/checkout@v4

      - name: Setup Python
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
          semgrep --version

      - name: Run Semgrep scan
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        run: |
          semgrep --config=auto "${{ inputs.working-directory }}" \
            --sarif --sarif-output=semgrep-report.sarif

      - name: Upload SARIF to GitHub Advanced Security
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
          category: semgrep-sast-analysis

      - name: Check for vulnerabilities
        id: check_vuln
        continue-on-error: ${{ ! (inputs.is-blocking == true) }}
        run: |
          if [ ! -f semgrep-report.sarif ]; then
            echo "end_msg='SARIF file not found.'" | tee -a "$GITHUB_OUTPUT"
          elif ! jq -e '.runs[0].results' semgrep-report.sarif >/dev/null 2>&1; then
            echo "end_msg='Invalid SARIF structure.'" | tee -a "$GITHUB_OUTPUT"
          else
            results_count=$(jq '.runs[0].results | length' semgrep-report.sarif)
            if [ "$results_count" -eq 0 ]; then
              echo "vulnerabilities_found=false" | tee -a "$GITHUB_OUTPUT"
              echo "end_msg='✅ No vulnerabilities found.'" | tee -a "$GITHUB_OUTPUT"
            else
              echo "vulnerabilities_found=true" | tee -a "$GITHUB_OUTPUT"
              echo "end_msg='🚨 Vulnerabilities found in scan results.'" | tee -a "$GITHUB_OUTPUT"
            fi
          fi

      - name: Stop workflow if blocking
        if: ${{ steps.check_vuln.outputs.vulnerabilities_found == 'true' && inputs.is-blocking == true }}
        run: |
          echo "End message: ${{ steps.check_vuln.outputs.end_msg }}"
          exit 1